(() => {
  "use strict";
  const STORAGE_KEY="rack-manager-v1-state",DEFAULT_SITE="未分類據點",DEFAULT_ROOM="未分類機房",$=id=>document.getElementById(id),norm=v=>String(v??"").trim(),uniq=arr=>[...new Set(arr.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"zh-Hant")),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  function readState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");}catch{return null;}}
  function activeRack(state){return state?.racks?.find(r=>r.id===state.activeRackId)||state?.racks?.[0]||null;}
  function siteOf(r){return norm(r?.siteName)||DEFAULT_SITE;} function roomOf(r){return norm(r?.roomName)||norm(r?.location)||DEFAULT_ROOM;}
  function sync(nextState,message){const input=$("jsonImport");if(!input){localStorage.setItem(STORAGE_KEY,JSON.stringify(nextState));return;}try{const file=new File([JSON.stringify(nextState)],"rack-manager-v21-sync.json",{type:"application/json"}),dt=new DataTransfer();dt.items.add(file);input.files=dt.files;const originalConfirm=window.confirm;let approve=true;window.confirm=function(text){if(approve&&String(text||"").includes("將匯入")){approve=false;window.confirm=originalConfirm;return true;}return originalConfirm.apply(this,arguments);};input.dispatchEvent(new Event("change",{bubbles:true}));setTimeout(()=>{if(window.confirm!==originalConfirm)window.confirm=originalConfirm;document.querySelectorAll("#toastStack .toast").forEach(t=>{if(t.textContent.includes("JSON 備份已匯入"))t.textContent=message;});},180);}catch(err){console.error("Rack Manager V2.1 sync failed",err);localStorage.setItem(STORAGE_KEY,JSON.stringify(nextState));}}
  let mode="edit",siteInput,roomInput,siteList,roomList;
  function build(){const form=$("rackForm"),grid=form?.querySelector(".form-grid");if(!form||!grid||$("v21RackSiteInput"))return;const s=document.createElement("label"),r=document.createElement("label");s.innerHTML=`據點<input class="field" id="v21RackSiteInput" list="v21RackSiteList" required maxlength="80" placeholder="選擇既有據點或輸入新名稱"><datalist id="v21RackSiteList"></datalist>`;r.innerHTML=`機房<input class="field" id="v21RackRoomInput" list="v21RackRoomList" required maxlength="80" placeholder="選擇既有機房或輸入新名稱"><datalist id="v21RackRoomList"></datalist>`;const first=grid.querySelector("label");first?first.after(s,r):grid.prepend(s,r);siteInput=$("v21RackSiteInput");roomInput=$("v21RackRoomInput");siteList=$("v21RackSiteList");roomList=$("v21RackRoomList");siteInput.addEventListener("input",()=>fillRooms(siteInput.value));form.addEventListener("submit",afterSave);}
  function fillSites(){const state=readState();if(siteList)siteList.innerHTML=uniq((state?.racks||[]).map(siteOf).filter(v=>v!==DEFAULT_SITE)).map(v=>`<option value="${esc(v)}"></option>`).join("");}
  function fillRooms(site){const state=readState();if(!roomList)return;const s=norm(site);let rooms=(state?.racks||[]).filter(r=>siteOf(r)===s).map(roomOf).filter(v=>v!==DEFAULT_ROOM);if(!rooms.length)rooms=(state?.racks||[]).map(roomOf).filter(v=>v!==DEFAULT_ROOM);roomList.innerHTML=uniq(rooms).map(v=>`<option value="${esc(v)}"></option>`).join("");}
  function prepare(which){build();const state=readState(),rack=activeRack(state);if(!rack||!siteInput||!roomInput)return;mode=which;fillSites();if(which==="new"){const ss=norm($("v2SiteSelect")?.value),sr=norm($("v2RoomSelect")?.value),site=(ss&&ss!==DEFAULT_SITE)?ss:((siteOf(rack)!==DEFAULT_SITE)?siteOf(rack):""),room=(sr&&sr!==DEFAULT_ROOM)?sr:((roomOf(rack)!==DEFAULT_ROOM)?roomOf(rack):"");siteInput.value=site;fillRooms(site);roomInput.value=site?room:"";}else{siteInput.value=siteOf(rack)===DEFAULT_SITE?"":siteOf(rack);fillRooms(siteInput.value);roomInput.value=roomOf(rack)===DEFAULT_ROOM?"":roomOf(rack);}}
  function afterSave(){const site=norm(siteInput?.value),room=norm(roomInput?.value);if(!site||!room)return;setTimeout(()=>{const state=readState(),rack=activeRack(state);if(!rack)return;rack.siteName=site;rack.roomName=room;rack.updatedAt=new Date().toISOString();state.version=2.1;sync(state,mode==="new"?"機櫃已建立並加入指定據點 / 機房":"機櫃歸屬已更新");},40);}
  function hook(){build();$("btnNewRack")?.addEventListener("click",()=>setTimeout(()=>prepare("new"),0));$("btnRackSettings")?.addEventListener("click",()=>setTimeout(()=>prepare("edit"),0));const modal=$("rackModal");if(modal)new MutationObserver(()=>{if(!modal.open)return;const isNew=$("rackModalEyebrow")?.textContent?.includes("NEW");setTimeout(()=>prepare(isNew?"new":"edit"),0);}).observe(modal,{attributes:true,attributeFilter:["open"]});const badge=document.querySelector("#v2Hierarchy .badge");if(badge)badge.textContent="V2.1";}
  hook();
})();