(() => {
  "use strict";
  const STORAGE_KEY = "rack-manager-v1-state";
  const DEFAULT_SITE = "未分類據點";
  const DEFAULT_ROOM = "未分類機房";
  const $ = id => document.getElementById(id);
  const norm = v => String(v ?? "").trim();
  const esc = s => String(s ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const clamp = (n,min,max) => Math.max(min,Math.min(max,n));
  const uid = prefix => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const TYPE_LABELS = {switch:"網路交換器",router:"路由器 / 防火牆",patch:"Patch Panel",cable:"理線架",server:"伺服器",nas:"NAS",ups:"UPS",pdu:"PDU",shelf:"層板 / 其他",other:"其他"};
  const INSTALL_LABELS = {rack:"機架式",shelf:"層板式",tower:"桌上型 / 塔式",external:"外部設備"};
  const style=document.createElement("style");
  style.textContent=`
    .v25-dialog{border:0;border-radius:16px;padding:0;box-shadow:0 26px 90px rgba(15,23,42,.36);background:#fff;max-height:calc(100vh - 28px);overflow:hidden}.v25-dialog::backdrop{background:rgba(15,23,42,.6);backdrop-filter:blur(2px)}
    .v25-dispatch{width:min(1120px,calc(100vw - 28px))}.v25-move{width:min(660px,calc(100vw - 28px))}.v25-device-form{width:min(860px,calc(100vw - 28px))}.v25-inner{padding:20px;display:flex;flex-direction:column;max-height:calc(100vh - 28px);box-sizing:border-box}
    .v25-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:14px}.v25-head h2{margin:2px 0 0;font-size:20px;color:#172033}.v25-kicker{font-size:9px;font-weight:900;letter-spacing:.12em;color:#94a3b8}.v25-close{border:0;background:#f1f5f9;width:32px;height:32px;border-radius:8px;font-size:20px;color:#64748b;cursor:pointer}
    .v25-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:12px}.v25-card{border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc;padding:9px 10px}.v25-card span{display:block;font-size:9px;color:#7c899a;font-weight:800}.v25-card strong{display:block;font-size:17px;color:#1e293b;margin-top:3px}
    .v25-toolbar{display:grid;grid-template-columns:minmax(240px,2fr) repeat(2,minmax(140px,1fr)) auto;gap:8px;margin-bottom:10px}.v25-toolbar .field{width:100%}.v25-toolbar .btn{white-space:nowrap}.v25-table-wrap{border:1px solid #e2e8f0;border-radius:11px;overflow:auto;max-height:60vh;min-height:260px}.v25-table{width:100%;border-collapse:collapse;font-size:11px}.v25-table th{position:sticky;top:0;z-index:2;background:#f8fafc;color:#64748b;font-size:9px;text-align:left;padding:9px 8px;border-bottom:1px solid #dbe3ed;white-space:nowrap}.v25-table td{padding:8px;border-bottom:1px solid #edf1f5;color:#334155;vertical-align:middle}.v25-table tbody tr:hover{background:#f8fbff}.v25-name strong{display:block;color:#1e293b;font-size:11px}.v25-name span{display:block;color:#94a3b8;font-size:9px;margin-top:2px}.v25-path{font-size:9px;color:#64748b;line-height:1.45}.v25-actions{display:flex;gap:5px;justify-content:flex-end;white-space:nowrap}.v25-actions .btn{min-height:28px;padding:4px 7px;font-size:9px}.v25-chip{display:inline-flex;align-items:center;border-radius:999px;padding:3px 7px;font-size:9px;font-weight:800;white-space:nowrap}.v25-chip.unassigned{background:#fef3c7;color:#92400e}.v25-empty{padding:34px 12px;text-align:center;color:#94a3b8;font-size:12px}.v25-note{font-size:10px;color:#7a8798;line-height:1.55;margin:7px 0 0}
    .v25-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.v25-grid.three{grid-template-columns:repeat(3,1fr)}.v25-grid label{font-size:10px;font-weight:800;color:#64748b;display:grid;gap:5px}.v25-grid .full{grid-column:1/-1}.v25-current{border:1px solid #e2e8f0;background:#f8fafc;border-radius:10px;padding:10px 11px;margin-bottom:12px}.v25-current strong{display:block;font-size:12px;color:#1e293b}.v25-current span{display:block;font-size:9px;color:#64748b;margin-top:3px}.v25-actions-row{display:flex;align-items:center;gap:8px;border-top:1px solid #edf1f5;padding-top:14px;margin-top:16px}.v25-actions-row .spacer{flex:1}.v25-slot-note{font-size:10px;min-height:16px;color:#64748b;margin-top:6px}.v25-slot-note.error{color:#b91c1c}.v25-inline-tools{display:flex;gap:6px;align-items:end}.v25-inline-tools label{flex:1}.v25-overview-link{margin-left:8px}
    @media(max-width:900px){.v25-toolbar{grid-template-columns:1fr 1fr}.v25-toolbar input{grid-column:1/-1}.v25-grid.three{grid-template-columns:1fr 1fr}}@media(max-width:620px){.v25-summary,.v25-grid,.v25-grid.three,.v25-toolbar{grid-template-columns:1fr}.v25-toolbar input{grid-column:auto}.v25-actions{flex-wrap:wrap}.v25-table-wrap{max-height:55vh}}
  `;document.head.appendChild(style);
  function readState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");}catch{return null;}}
  function siteOf(r){return norm(r?.siteName)||DEFAULT_SITE;}function roomOf(r){return norm(r?.roomName)||norm(r?.location)||DEFAULT_ROOM;}
  function toast(message,type="success"){const stack=$("toastStack");if(!stack)return;const el=document.createElement("div");el.className=`toast ${type}`;el.textContent=message;stack.appendChild(el);setTimeout(()=>el.remove(),2800);}
  function ensurePool(state){if(!Array.isArray(state.unassignedDevices))state.unassignedDevices=[];return state.unassignedDevices;}
  function defaultWidth(installation){if(installation==="shelf")return 58;if(installation==="tower")return 36;return 100;}
  function horizontalRange(widthPct,xPct){const width=clamp(Number(widthPct)||100,20,100),pos=clamp(Number(xPct)||0,0,100),start=(100-width)*(pos/100);return{start,end:start+width};}
  function rangesOverlap(a,b){return Math.max(a.start,b.start)<Math.min(a.end,b.end)-0.15;}
  function canPlace(rack,device,topU,side,ignoreId=null){if(device.installation==="external")return true;const h=Math.max(1,Number(device.height)||1),top=Number(topU),bottom=top-h+1;if(!Number.isFinite(top)||top>Number(rack.units)||bottom<1)return false;const installation=device.installation||"rack",candidateRange=horizontalRange(installation==="rack"?100:(device.widthPct||defaultWidth(installation)),installation==="rack"?50:(device.xPct??50));return !(rack.devices||[]).some(d=>{if(d.id===ignoreId||d.installation==="external"||(d.side||"front")!==side)return false;const dTop=Number(d.u)||1,dHeight=Math.max(1,Number(d.height)||1),dBottom=dTop-dHeight+1,verticalOverlap=Math.max(bottom,dBottom)<=Math.min(top,dTop);if(!verticalOverlap)return false;if(installation==="rack"||d.installation==="rack")return true;return rangesOverlap(candidateRange,horizontalRange(d.widthPct||defaultWidth(d.installation),d.xPct??50));});}
  function findFreeTopU(rack,device,side,ignoreId=null){if(device.installation==="external")return null;const h=Math.max(1,Number(device.height)||1);for(let top=Number(rack.units)||42;top>=h;top--)if(canPlace(rack,device,top,side,ignoreId))return top;return null;}
  function uLabel(d){if(d.installation==="external")return"周邊";if(d.u==null)return"未上架";const top=Number(d.u)||1,h=Math.max(1,Number(d.height)||1),bottom=top-h+1;return h>1?`U${bottom}–U${top}`:`U${top}`;}
  function syncStateIntoCore(nextState,message,callback){const input=$("jsonImport");if(!input){localStorage.setItem(STORAGE_KEY,JSON.stringify(nextState));toast(message);callback?.();return;}try{const file=new File([JSON.stringify(nextState)],"rack-manager-v25-sync.json",{type:"application/json"}),dt=new DataTransfer();dt.items.add(file);input.files=dt.files;const originalConfirm=window.confirm;let approve=true;window.confirm=function(text){if(approve&&String(text||"").includes("將匯入")){approve=false;window.confirm=originalConfirm;return true;}return originalConfirm.apply(this,arguments);};input.dispatchEvent(new Event("change",{bubbles:true}));setTimeout(()=>{if(window.confirm!==originalConfirm)window.confirm=originalConfirm;document.querySelectorAll("#toastStack .toast").forEach(t=>{if(t.textContent.includes("JSON 備份已匯入"))t.textContent=message;});callback?.();},220);}catch(err){console.error("Rack Manager V2.5 sync failed",err);localStorage.setItem(STORAGE_KEY,JSON.stringify(nextState));toast("資料已儲存，請重新整理頁面","error");callback?.();}}
  function installedRows(state){const out=[];(state?.racks||[]).forEach(r=>(r.devices||[]).forEach(d=>out.push({kind:"mounted",rack:r,d,site:siteOf(r),room:roomOf(r)})));return out;}function poolRows(state){return ensurePool(state).map(d=>({kind:"unassigned",rack:null,d,site:"",room:""}));}function allRows(state){return[...installedRows(state),...poolRows(state)];}
  function installTopButton(){const actions=document.querySelector(".top-actions");if(!actions||$("v25DispatchBtn"))return;const b=document.createElement("button");b.className="btn v25-top-btn";b.id="v25DispatchBtn";b.textContent="設備調度";const overview=$("v24OverviewBtn");if(overview)overview.after(b);else actions.insertBefore(b,actions.firstChild);b.addEventListener("click",openDispatch);}
  function installOverviewShortcut(){const dialog=$("v24Overview");if(!dialog||$("v25OverviewDispatch"))return;const head=dialog.querySelector(".v24-head");if(!head)return;const close=$("v24OverviewClose"),b=document.createElement("button");b.className="btn v25-overview-link";b.id="v25OverviewDispatch";b.textContent="設備調度";b.addEventListener("click",()=>{dialog.close();openDispatch();});close?.before(b);}
  let dispatchDialog,dispatchBody,dispatchSearch,dispatchKind,dispatchSite,dispatchCount;
  function buildDispatch(){if($("v25Dispatch")){dispatchDialog=$("v25Dispatch");return;}dispatchDialog=document.createElement("dialog");dispatchDialog.className="v25-dialog v25-dispatch";dispatchDialog.id="v25Dispatch";dispatchDialog.innerHTML=`<div class="v25-inner"><div class="v25-head"><div><span class="v25-kicker">DEVICE DISPATCH</span><h2>設備調度</h2></div><button class="v25-close" id="v25DispatchClose">×</button></div><div class="v25-summary" id="v25Summary"></div><div class="v25-toolbar"><input class="field" id="v25Search" placeholder="搜尋設備名稱、IP、Hostname、型號、序號、資產編號…"><select class="field" id="v25Kind"><option value="">全部設備</option><option value="mounted">已上架</option><option value="unassigned">未上架</option></select><select class="field" id="v25Site"><option value="">全部據點</option></select><button class="btn primary" id="v25NewUnassigned">＋ 新增未上架設備</button></div><div class="v25-note" id="v25Count"></div><div class="v25-table-wrap"><table class="v25-table"><thead><tr><th>設備</th><th>類型</th><th>IP / Hostname</th><th>目前位置</th><th>狀態</th><th style="text-align:right">操作</th></tr></thead><tbody id="v25Body"></tbody></table></div></div>`;document.body.appendChild(dispatchDialog);dispatchBody=$("v25Body");dispatchSearch=$("v25Search");dispatchKind=$("v25Kind");dispatchSite=$("v25Site");dispatchCount=$("v25Count");$("v25DispatchClose").onclick=()=>dispatchDialog.close();$("v25NewUnassigned").onclick=()=>openPoolEditor(null);dispatchSearch.addEventListener("input",renderDispatch);dispatchKind.addEventListener("change",renderDispatch);dispatchSite.addEventListener("change",renderDispatch);}
  function openDispatch(){buildDispatch();refreshDispatchOptions();renderDispatch();dispatchDialog.showModal();setTimeout(()=>dispatchSearch.focus(),30);}
  function refreshDispatchOptions(){const state=readState();if(!state)return;const previous=dispatchSite.value,sites=[...new Set((state.racks||[]).map(siteOf))].sort((a,b)=>a.localeCompare(b,"zh-Hant"));dispatchSite.innerHTML=`<option value="">全部據點</option>`+sites.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join("");if(sites.includes(previous))dispatchSite.value=previous;}
  function renderDispatch(){const state=readState();if(!state||!dispatchBody)return;const mounted=installedRows(state),pool=poolRows(state),all=[...mounted,...pool];$("v25Summary").innerHTML=`<div class="v25-card"><span>全部設備</span><strong>${all.length}</strong></div><div class="v25-card"><span>已上架</span><strong>${mounted.length}</strong></div><div class="v25-card"><span>未上架</span><strong>${pool.length}</strong></div>`;const q=norm(dispatchSearch.value).toLowerCase(),kind=dispatchKind.value,site=dispatchSite.value;let rows=all.filter(x=>{if(kind&&x.kind!==kind)return false;if(site&&(x.kind!=="mounted"||x.site!==site))return false;if(!q)return true;const hay=[x.d.name,x.d.ip,x.d.hostname,x.d.model,x.d.serial,x.d.asset,x.d.brand,x.d.mac,x.d.owner,x.d.status,TYPE_LABELS[x.d.type],x.site,x.room,x.rack?.name].map(v=>norm(v).toLowerCase()).join(" ");return hay.includes(q);});rows.sort((a,b)=>a.kind!==b.kind?(a.kind==="unassigned"?1:-1):(a.site||"").localeCompare(b.site||"","zh-Hant")||(a.room||"").localeCompare(b.room||"","zh-Hant")||String(a.rack?.name||"").localeCompare(String(b.rack?.name||""),"zh-Hant")||String(a.d.name||"").localeCompare(String(b.d.name||""),"zh-Hant"));dispatchCount.textContent=`顯示 ${rows.length} / ${all.length} 台設備`;dispatchBody.innerHTML="";if(!rows.length){dispatchBody.innerHTML=`<tr><td colspan="6"><div class="v25-empty">沒有符合條件的設備</div></td></tr>`;return;}rows.forEach(x=>{const tr=document.createElement("tr"),pos=x.kind==="mounted"?`<strong>${esc(x.rack.name||"機櫃")}</strong><div class="v25-path">${esc(x.site)} › ${esc(x.room)} › ${esc(x.d.side==="rear"?"REAR":"FRONT")} › ${esc(uLabel(x.d))}</div>`:`<span class="v25-chip unassigned">未上架</span>`,actions=x.kind==="mounted"?`<button class="btn locate">定位</button><button class="btn move">移動</button><button class="btn unmount">移出</button>`:`<button class="btn primary mount">上架</button><button class="btn edit">編輯</button><button class="btn danger delete">刪除</button>`;tr.innerHTML=`<td class="v25-name"><strong>${esc(x.d.name||"未命名設備")}</strong><span>${esc([x.d.brand,x.d.model].filter(Boolean).join(" · ")||"—")}</span></td><td>${esc(TYPE_LABELS[x.d.type]||x.d.type||"其他")}<div class="v25-path">${esc(INSTALL_LABELS[x.d.installation]||"機架式")} · ${esc(String(x.d.height||1))}U</div></td><td>${esc(x.d.ip||"—")}<div class="v25-path">${esc(x.d.hostname||"")}</div></td><td>${pos}</td><td>${esc(x.d.status||"正常")}</td><td><div class="v25-actions">${actions}</div></td>`;if(x.kind==="mounted"){tr.querySelector(".locate").onclick=()=>locateDevice(x.rack.id,x.d);tr.querySelector(".move").onclick=()=>openMoveDialog("mounted",x.rack.id,x.d.id);tr.querySelector(".unmount").onclick=()=>moveToPool(x.rack.id,x.d.id);}else{tr.querySelector(".mount").onclick=()=>openMoveDialog("unassigned","",x.d.id);tr.querySelector(".edit").onclick=()=>openPoolEditor(x.d.id);tr.querySelector(".delete").onclick=()=>deletePoolDevice(x.d.id);}dispatchBody.appendChild(tr);});}
  function locateDevice(rackId,d){dispatchDialog?.close();const select=$("rackSelect");if(!select)return;if(select.value!==rackId){select.value=rackId;select.dispatchEvent(new Event("change",{bubbles:true}));}setTimeout(()=>{if(d.installation!=="external"){const face=document.querySelector(`.face-toggle button[data-face="${d.side||"front"}"]`);if(face&&!face.classList.contains("active"))face.click();}setTimeout(()=>{let target=null;try{target=document.querySelector(`#rackGrid .rack-device[data-id="${CSS.escape(String(d.id))}"]`);}catch{}if(!target)target=[...document.querySelectorAll("#deviceList > *")].find(el=>el.textContent.includes(d.name||""));target?.click();target?.scrollIntoView({behavior:"smooth",block:"center"});},120);},100);}
  let poolEditor,poolEditingId=null;
  function buildPoolEditor(){if($("v25PoolEditor")){poolEditor=$("v25PoolEditor");return;}poolEditor=document.createElement("dialog");poolEditor.className="v25-dialog v25-device-form";poolEditor.id="v25PoolEditor";poolEditor.innerHTML=`<form class="v25-inner" id="v25PoolForm"><div class="v25-head"><div><span class="v25-kicker">UNASSIGNED DEVICE</span><h2 id="v25PoolTitle">新增未上架設備</h2></div><button type="button" class="v25-close" id="v25PoolClose">×</button></div><div class="v25-grid three"><label class="full">設備名稱<input class="field" id="v25Name" required maxlength="80"></label><label>類型<select class="field" id="v25Type">${Object.entries(TYPE_LABELS).map(([k,v])=>`<option value="${k}">${v}</option>`).join("")}</select></label><label>安裝形式<select class="field" id="v25Installation"><option value="rack">機架式</option><option value="shelf">層板式</option><option value="tower">桌上型 / 塔式</option><option value="external">外部設備</option></select></label><label>高度（U）<input class="field" id="v25Height" type="number" min="1" max="20" value="1" required></label><label>廠牌<input class="field" id="v25Brand" maxlength="80"></label><label>型號<input class="field" id="v25Model" maxlength="100"></label><label>序號<input class="field" id="v25Serial" maxlength="100"></label><label>資產編號<input class="field" id="v25Asset" maxlength="100"></label><label>Hostname<input class="field" id="v25Hostname" maxlength="100"></label><label>管理 IP<input class="field" id="v25Ip" maxlength="60"></label><label>MAC Address<input class="field" id="v25Mac" maxlength="60"></label><label>VLAN<input class="field" id="v25Vlan" maxlength="60"></label><label>管理 Port<input class="field" id="v25Port" maxlength="60"></label><label>購買日期<input class="field" id="v25Purchase" type="date"></label><label>保固期限<input class="field" id="v25Warranty" type="date"></label><label>負責單位<input class="field" id="v25Owner" maxlength="100"></label><label>狀態<select class="field" id="v25Status"><option>正常</option><option>備用</option><option>維修</option><option>停用</option></select></label><label class="full">備註<textarea class="field" id="v25Note" rows="3" maxlength="800"></textarea></label></div><div class="v25-actions-row"><span class="v25-note">未上架設備不佔用任何 Rack / U 位，之後可從設備調度執行「上架」。</span><span class="spacer"></span><button type="button" class="btn" id="v25PoolCancel">取消</button><button class="btn primary" type="submit">儲存</button></div></form>`;document.body.appendChild(poolEditor);$("v25PoolClose").onclick=$("v25PoolCancel").onclick=()=>poolEditor.close();$("v25Installation").addEventListener("change",updatePoolHeight);$("v25PoolForm").addEventListener("submit",savePoolDevice);}
  function updatePoolHeight(){const external=$("v25Installation").value==="external";$("v25Height").disabled=external;if(external)$("v25Height").value="1";}
  function openPoolEditor(id){buildPoolEditor();poolEditingId=id||null;const state=readState();if(!state)return;const d=id?ensurePool(state).find(x=>x.id===id):null;$("v25PoolTitle").textContent=d?"編輯未上架設備":"新增未上架設備";$("v25Name").value=d?.name||"";$("v25Type").value=d?.type||"other";$("v25Installation").value=d?.installation||"rack";$("v25Height").value=String(d?.height||1);$("v25Brand").value=d?.brand||"";$("v25Model").value=d?.model||"";$("v25Serial").value=d?.serial||"";$("v25Asset").value=d?.asset||"";$("v25Hostname").value=d?.hostname||"";$("v25Ip").value=d?.ip||"";$("v25Mac").value=d?.mac||"";$("v25Vlan").value=d?.vlan||"";$("v25Port").value=d?.port||"";$("v25Purchase").value=d?.purchaseDate||"";$("v25Warranty").value=d?.warrantyDate||"";$("v25Owner").value=d?.owner||"";$("v25Status").value=d?.status||"正常";$("v25Note").value=d?.note||"";updatePoolHeight();poolEditor.showModal();setTimeout(()=>$("v25Name").focus(),30);}
  function savePoolDevice(e){e.preventDefault();const state=readState();if(!state)return;const pool=ensurePool(state),installation=$("v25Installation").value,height=installation==="external"?1:clamp(parseInt($("v25Height").value)||1,1,20);let d=poolEditingId?pool.find(x=>x.id===poolEditingId):null;if(!d){d={id:uid("dev"),createdAt:new Date().toISOString(),u:null,side:"front",placement:"",locked:false,xPct:50};pool.push(d);}Object.assign(d,{name:norm($("v25Name").value)||"未命名設備",type:$("v25Type").value,installation,height,u:null,widthPct:installation==="rack"?100:defaultWidth(installation),xPct:Number.isFinite(Number(d.xPct))?Number(d.xPct):50,brand:norm($("v25Brand").value),model:norm($("v25Model").value),serial:norm($("v25Serial").value),asset:norm($("v25Asset").value),hostname:norm($("v25Hostname").value),ip:norm($("v25Ip").value),mac:norm($("v25Mac").value),vlan:norm($("v25Vlan").value),port:norm($("v25Port").value),purchaseDate:$("v25Purchase").value||"",warrantyDate:$("v25Warranty").value||"",owner:norm($("v25Owner").value),status:$("v25Status").value||"正常",note:norm($("v25Note").value),updatedAt:new Date().toISOString(),unassignedAt:d.unassignedAt||new Date().toISOString()});poolEditor.close();syncStateIntoCore(state,poolEditingId?"未上架設備已更新":"未上架設備已建立",()=>{refreshDispatchOptions();renderDispatch();});}
  function deletePoolDevice(id){const state=readState();if(!state)return;const d=ensurePool(state).find(x=>x.id===id);if(!d)return;if(!confirm(`確定刪除未上架設備「${d.name}」？`))return;state.unassignedDevices=ensurePool(state).filter(x=>x.id!==id);syncStateIntoCore(state,"未上架設備已刪除",()=>renderDispatch());}
  function moveToPool(rackId,deviceId){const state=readState(),rack=(state?.racks||[]).find(r=>r.id===rackId);if(!rack)return;const d=(rack.devices||[]).find(x=>x.id===deviceId);if(!d)return;if(!confirm(`確定將「${d.name}」移出 ${rack.name}，放到未上架設備區？`))return;rack.devices=(rack.devices||[]).filter(x=>x.id!==deviceId);rack.updatedAt=new Date().toISOString();const moved=JSON.parse(JSON.stringify(d));moved.u=null;moved.unassignedAt=new Date().toISOString();moved.lastRack={rackId:rack.id,rackName:rack.name,site:siteOf(rack),room:roomOf(rack)};ensurePool(state).push(moved);syncStateIntoCore(state,`${d.name} 已移到未上架設備`,()=>{refreshDispatchOptions();renderDispatch();});}
  let moveDialog,moveMode="",moveSourceRackId="",moveDeviceId="";
  function buildMoveDialog(){if($("v25Move")){moveDialog=$("v25Move");return;}moveDialog=document.createElement("dialog");moveDialog.className="v25-dialog v25-move";moveDialog.id="v25Move";moveDialog.innerHTML=`<form class="v25-inner" id="v25MoveForm"><div class="v25-head"><div><span class="v25-kicker">RACK ASSIGNMENT</span><h2 id="v25MoveTitle">移動設備</h2></div><button type="button" class="v25-close" id="v25MoveClose">×</button></div><div class="v25-current" id="v25MoveCurrent"></div><div class="v25-grid"><label>目標據點<select class="field" id="v25TargetSite" required></select></label><label>目標機房<select class="field" id="v25TargetRoom" required></select></label><label class="full">目標機櫃<select class="field" id="v25TargetRack" required></select></label><label>安裝面<select class="field" id="v25TargetSide"><option value="front">FRONT 正面</option><option value="rear">REAR 背面</option></select></label><div class="v25-inline-tools"><label>最高 U 位<input class="field" id="v25TargetU" type="number" min="1"></label><button type="button" class="btn" id="v25AutoSlot">自動找空位</button></div></div><div class="v25-slot-note" id="v25SlotNote"></div><p class="v25-note">「最高 U 位」採目前系統的定位方式。例如 2U 設備填 U30，實際佔用 U30～U29。</p><div class="v25-actions-row"><button type="button" class="btn" id="v25MoveCancel">取消</button><span class="spacer"></span><button class="btn primary" type="submit">確認移動</button></div></form>`;document.body.appendChild(moveDialog);$("v25MoveClose").onclick=$("v25MoveCancel").onclick=()=>moveDialog.close();$("v25TargetSite").addEventListener("change",()=>{fillMoveRooms();fillMoveRacks();autoSlot();});$("v25TargetRoom").addEventListener("change",()=>{fillMoveRacks();autoSlot();});$("v25TargetRack").addEventListener("change",autoSlot);$("v25TargetSide").addEventListener("change",autoSlot);$("v25TargetU").addEventListener("input",validateSlot);$("v25AutoSlot").onclick=autoSlot;$("v25MoveForm").addEventListener("submit",submitMove);}
  function getMoveContext(){const state=readState();if(!state)return null;if(moveMode==="mounted"){const source=(state.racks||[]).find(r=>r.id===moveSourceRackId),device=source?.devices?.find(d=>d.id===moveDeviceId);return device?{state,source,device}:null;}const device=ensurePool(state).find(d=>d.id===moveDeviceId);return device?{state,source:null,device}:null;}
  function openMoveDialog(mode,rackId,deviceId){buildMoveDialog();moveMode=mode;moveSourceRackId=rackId||"";moveDeviceId=deviceId;const ctx=getMoveContext();if(!ctx)return;const{state,source,device}=ctx;$("v25MoveTitle").textContent=mode==="mounted"?"移動設備":"未上架設備上架";$("v25MoveCurrent").innerHTML=`<strong>${esc(device.name)}</strong><span>${esc(TYPE_LABELS[device.type]||"設備")} · ${esc(INSTALL_LABELS[device.installation]||"機架式")} · ${device.installation==="external"?"周邊設備":`${device.height||1}U`}${source?` · 目前：${esc(siteOf(source))} › ${esc(roomOf(source))} › ${esc(source.name)} › ${esc(uLabel(device))}`:" · 目前：未上架"}</span>`;const sites=[...new Set((state.racks||[]).map(siteOf))].sort((a,b)=>a.localeCompare(b,"zh-Hant"));$("v25TargetSite").innerHTML=sites.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join("");const preferred=source?siteOf(source):(device.lastRack?.site||sites[0]);$("v25TargetSite").value=sites.includes(preferred)?preferred:sites[0];fillMoveRooms(source?roomOf(source):device.lastRack?.room);fillMoveRacks(source?.id||device.lastRack?.rackId);$("v25TargetSide").value=device.side==="rear"?"rear":"front";updatePositionControls();autoSlot();moveDialog.showModal();}
  function fillMoveRooms(preferred=""){const state=readState(),site=$("v25TargetSite").value;if(!state)return;const rooms=[...new Set((state.racks||[]).filter(r=>siteOf(r)===site).map(roomOf))].sort((a,b)=>a.localeCompare(b,"zh-Hant"));$("v25TargetRoom").innerHTML=rooms.map(r=>`<option value="${esc(r)}">${esc(r)}</option>`).join("");if(rooms.includes(preferred))$("v25TargetRoom").value=preferred;}
  function fillMoveRacks(preferred=""){const state=readState(),site=$("v25TargetSite").value,room=$("v25TargetRoom").value;if(!state)return;const racks=(state.racks||[]).filter(r=>siteOf(r)===site&&roomOf(r)===room);$("v25TargetRack").innerHTML=racks.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} · ${Number(r.units)||42}U</option>`).join("");if(racks.some(r=>r.id===preferred))$("v25TargetRack").value=preferred;updatePositionControls();}
  function updatePositionControls(){const ctx=getMoveContext();if(!ctx)return;const external=ctx.device.installation==="external";$("v25TargetSide").disabled=external;$("v25TargetU").disabled=external;$("v25AutoSlot").disabled=external;if(external){$("v25TargetU").value="";$("v25SlotNote").textContent="外部設備不佔用 U 位。";}}
  function autoSlot(){const ctx=getMoveContext();if(!ctx)return;const{state,source,device}=ctx;updatePositionControls();if(device.installation==="external"){validateSlot();return;}const rack=(state.racks||[]).find(r=>r.id===$("v25TargetRack").value);if(!rack){$("v25SlotNote").textContent="此機房沒有可用機櫃";return;}const side=$("v25TargetSide").value,ignore=source?.id===rack.id?device.id:null,free=findFreeTopU(rack,device,side,ignore);$("v25TargetU").max=String(rack.units);if(free==null){$("v25TargetU").value="";$("v25SlotNote").textContent="找不到足夠的連續空間";$("v25SlotNote").classList.add("error");}else{$("v25TargetU").value=String(free);validateSlot();}}
  function validateSlot(){const ctx=getMoveContext();if(!ctx)return false;const{state,source,device}=ctx,note=$("v25SlotNote");note.classList.remove("error");if(device.installation==="external"){note.textContent="外部設備將加入目標機櫃的周邊設備區。";return true;}const rack=(state.racks||[]).find(r=>r.id===$("v25TargetRack").value),side=$("v25TargetSide").value,u=Number($("v25TargetU").value);if(!rack){note.textContent="請選擇目標機櫃";note.classList.add("error");return false;}$("v25TargetU").max=String(rack.units);const ignore=source?.id===rack.id?device.id:null,ok=canPlace(rack,device,u,side,ignore);if(ok){const h=Math.max(1,Number(device.height)||1),bottom=u-h+1;note.textContent=h>1?`可放置：U${u}～U${bottom}`:`可放置：U${u}`;return true;}note.textContent="此 U 位空間不足、超出機櫃範圍或與其他設備重疊";note.classList.add("error");return false;}
  function submitMove(e){e.preventDefault();const ctx=getMoveContext();if(!ctx)return;const{state,source,device}=ctx,target=(state.racks||[]).find(r=>r.id===$("v25TargetRack").value);if(!target){toast("請選擇目標機櫃","error");return;}const external=device.installation==="external",side=external?(device.side||"front"):$("v25TargetSide").value,u=external?null:Number($("v25TargetU").value);if(!external&&!validateSlot()){toast("目標 U 位無法放置此設備","error");return;}if(source)source.devices=(source.devices||[]).filter(d=>d.id!==device.id);else state.unassignedDevices=ensurePool(state).filter(d=>d.id!==device.id);device.side=side;device.u=u;device.updatedAt=new Date().toISOString();delete device.unassignedAt;delete device.lastRack;target.devices=Array.isArray(target.devices)?target.devices:[];target.devices.push(device);target.updatedAt=new Date().toISOString();if(source&&source.id!==target.id)source.updatedAt=new Date().toISOString();state.activeRackId=target.id;if(!external)state.activeFace=side;moveDialog.close();const message=moveMode==="unassigned"?`${device.name} 已上架到 ${target.name}`:`${device.name} 已移動到 ${target.name}`;syncStateIntoCore(state,message,()=>{refreshDispatchOptions();renderDispatch();});}
  function updateVersion(){const badge=document.querySelector("#v2Hierarchy .v231-version-badge")||document.querySelector("#v2Hierarchy .badge");if(badge)badge.textContent="V2.5";}
  function init(){installTopButton();updateVersion();document.addEventListener("click",e=>{if(e.target.closest?.("#v24OverviewBtn"))setTimeout(installOverviewShortcut,0);});}
  init();
})();
